// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ApolloProvider = require("reason-apollo/src/ApolloProvider.bs.js");
var Client$ReactTemplate = require("./Client.bs.js");
var Component1$ReactTemplate = require("./Component1.bs.js");
var OpenIssueList$ReactTemplate = require("./OpenIssueList.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ApolloProvider.make(Client$ReactTemplate.instance, /* array */[
              React.createElement("h1", undefined, "Goals 2 + 3"),
              ReasonReact.element(/* None */0, /* None */0, Component1$ReactTemplate.make(/* array */[])),
              React.createElement("h1", undefined, "Goals 4"),
              ReasonReact.element(/* None */0, /* None */0, OpenIssueList$ReactTemplate.make(/* array */[]))
            ])), "index2");

/*  Not a pure module */
